import {VERSIONS, METRICS} from './scoring.mjs';
import {isEnumValue, normalizeEnum, REQUIREMENT_LIMITATION_STATUSES} from './enums.mjs';

export const REQUIREMENTS = [
  ['communication_access','Primary communication-tool access','Required'], ['history_30_days','Minimum 30 days of operational history','Required'], ['founder_calendar','Founder calendar covering two representative weeks','Required'], ['task_access','Task-management access','Required'], ['operational_boards','Relevant operational boards','Required'], ['staff_interviews','3-5 staff interviews','Required'], ['founder_intake','60-90 minute founder intake','Required'], ['company_structure','Company hierarchy or staff structure','Required'], ['documentation_access','Internal documentation access','Strongly recommended'], ['tool_inventory','Active-tool inventory','Strongly recommended'], ['org_chart','Org chart or reporting description','Strongly recommended'], ['sprint_reports','Sprint reports or retrospectives','Useful'], ['process_docs','Process documentation','Useful'], ['onboarding_records','Onboarding records','Useful'], ['tool_usage','Tool-usage data','Useful'], ['prior_assessments','Prior operational assessments','Useful'], ['workflow_surveys','Existing workflow surveys','Useful']
];
const q=(title,question,followUps=[],quantitative=null)=>({title,question,followUps,quantitative});
export const FOUNDER_SECTIONS = [
  q('Company in Its Current Form','Tell me about the company as it operates today.',['What does the company sell and to whom?','How does work move from demand to delivery?','What is growing or becoming harder?']),
  q('Engagement Trigger','What happened that made this diagnosis feel necessary now?',['Was there a specific failure, delay, complaint, or missed opportunity?','What happens if nothing changes?','What should the diagnosis make visible?']),
  q('Intended Versus Actual Operating Model','How is the company supposed to operate, and how does work actually happen?',['Where does reality differ most from the intended model?','Which responsibilities are clear on paper but unclear in practice?','What happens outside the formal system?']),
  q('Founder’s Intended Role','What do you believe your role should be at this stage of the company?',['What work should only you do?','Which responsibilities should no longer require you?']),
  q('Founder’s Actual Week','Walk me through what a normal week actually looks like.',['What is planned versus unexpected?','What regularly displaces intended work?','What creates the most context switching?']),
  q('Operational Interruptions','Think about the last five workdays. How many times were you interrupted for operational guidance, approval, information, ownership resolution, or work unblocking?',['Who usually contacts you and what do they need?','Why can’t they proceed without you?','Does the same issue return?'],{unit:'interruptions / founder workday',healthy:'≤ 3',severe:'≥ 9',min:0,step:0.1}),
  q('Decision Bottlenecks','What kinds of decisions consistently return to you before work can continue?',['Which decisions legitimately require you?','How long does work wait and how many people are affected?','What is the most recent example?'],{unit:'blocked person-hours / contributor / week',healthy:'≤ 2',severe:'≥ 6',min:0,step:0.1}),
  q('Founder-Unavailable Test','If you were completely unavailable for two weeks, what work would stop, slow down, or become risky?',['Which decisions would accumulate?','What knowledge would be missing?','Who becomes the substitute decision-maker?']),
  q('Critical Recurring Processes','Which recurring processes are most important to the company’s ability to operate?',['Identify at least five.','Who owns each process and where is it documented?','Could each be completed correctly without you?']),
  q('Knowledge Location','Where does the company’s important operational knowledge currently live?',['Which source is authoritative?','How do people know it is current?','Who is the unofficial source of truth?']),
  q('Documentation Reality','How would you describe the current documentation system?',['What is documented well, poorly, or not at all?','Who owns updates?','Which five documents would be useful to test?']),
  q('Company Structure','Walk me through the current team structure and reporting relationships.',['Where is ownership shared or missing?','Who acts as a cross-functional connector?','Who receives the most questions?']),
  q('Interview Participant Selection','Which team members experience different parts of how work actually moves through the company?',['Include varied functions, seniority, tenure, founder proximity, and handoff roles.','Who can provide a perspective unlike yours?']),
  q('Recent Onboarding Cases','Who are the most recent people to join the company or move into a substantially new role?',['When did they reach independent performance?','What slowed onboarding?','What records can be reviewed?'],{unit:'calendar days to autonomy',healthy:'≤ 14',severe:'≥ 42',min:0,step:1}),
  q('Recent Project Sample','Which recent projects best represent how work normally moves through the company?',['Identify at least five recent, material, traceable, and varied projects.','Where did each stop, change, or require rework?']),
  q('Forced Stops','Where does work most commonly stop because something required is missing?',['What dependency is usually missing?','How many times did this happen on a representative project?','Are stops visible in the task system?'],{unit:'forced stops / project',healthy:'≤ 1',severe:'≥ 3',min:0,step:0.1}),
  q('Rework','What work is most commonly redone because the initial brief, decision, handoff, or information was insufficient?',['What is the most recent example?','Exclude productive iteration and genuinely new information.'],{unit:'% of project effort',healthy:'≤ 10%',severe:'≥ 30%',min:0,max:100,step:1}),
  q('Alignment Drift','How often does work need to pause, reverse, or materially redirect because people discover they were not aligned on purpose, priority, scope, or success criteria?',['How many times in the last month and across how many projects?','Was the original direction unclear or did new information emerge?'],{unit:'events / project / month',healthy:'≤ 1',severe:'≥ 3',min:0,step:0.1}),
  q('Active-Tool Inventory','Walk me through the tools the company actively uses and what each is supposed to do.',['Who owns each tool?','Which workflows, overlaps, integrations, and workarounds matter?']),
  q('Tool Switching','Which recurring workflows require people to move between several tools to complete one piece of work?',['Which transitions are avoidable?','Where is information copied or context reconstructed?'],{unit:'avoidable minutes / contributor / workday',healthy:'≤ 15',severe:'≥ 45',min:0,max:1440,step:1}),
  q('Integration Integrity','Which tools are supposed to exchange information automatically?',['Which flows are operationally critical?','Where does synchronization fail?','Which three or more flows should be tested?'],{unit:'% successful core data flows',healthy:'≥ 95%',severe:'0%',min:0,max:100,step:1}),
  q('Tool Utility and Deadweight','Which tools may be overlapping, underused, maintained without a clear owner, or creating more burden than value?',['What unique function does each provide?','What would break if it were removed?','Which are consolidation candidates?'],{unit:'% of active tools',healthy:'≤ 20%',severe:'≥ 60%',min:0,max:100,step:1}),
  q('Critical Handoffs','Where does work most importantly move between people, roles, or teams?',['Identify at least five recent handoffs.','What context, deadline, and success criteria should transfer?']),
  q('Handoff Failure Patterns','What most commonly gets lost, misunderstood, or reconstructed when work changes hands?',['Are purpose, deadlines, dependencies, and success criteria clear?','What compensating behavior keeps handoffs functioning?'],{unit:'context-loss rating (1–5)',healthy:'≤ 2',severe:'5',min:1,max:5,step:1}),
  q('How the Company Keeps Work Moving','When the formal system is not enough, what do you or the team do to keep work moving?',['What problem does each workaround compensate for?','Who performs it and what happens if it stops?']),
  q('Prior Improvement Attempts','What have you already tried to improve the way the company operates?',['What changed and what did not?','Why did the attempt succeed or fail?','Did it add tools or process layers?']),
  q('Scalability Ceiling','If the company doubled its workload without doubling its team, what would break first?',['Which dependency would fail first?','What capacity is currently hidden by human compensation?']),
  q('Highest-Leverage Change','If you could permanently fix one part of how the company operates, what would you choose?',['Why that one?','What becomes possible if it is fixed?']),
  q('Successful Diagnosis','At the end of this diagnosis, what would make you feel that the work was useful?',['What decisions should the findings enable?','What would a useful report clarify?']),
  q('Missing Context','What should I understand about the company’s operations that I haven’t asked about?')
];

export const STAFF_PROMPTS = [
  q('Typical Work','Walk me through what a typical week looks like for you.',['What responsibilities occupy most of your time?','Which workflows and teams do you interact with most?']),
  q('Start and End of Day','What does your workday usually start with, and what does it usually end with?',['Which systems do you check?','What remains unresolved at day’s end?']),
  q('Decision Routing','When you need a decision to move work forward, who do you go to?',['How do you know who has authority?','Which decisions return to the founder?']),
  q('Blocked Time Waiting for Decisions','Think about the most recent time your work was blocked because you needed a founder-level decision, approval, or clarification. What happened?',['Were you completely blocked?','How many productive hours were lost?','How often does this happen?'],{unit:'blocked person-hours / week',healthy:'≤ 2',severe:'≥ 6',min:0,step:0.1}),
  q('Founder Interruptions','How often do you personally need to interrupt or contact the founder for operational guidance?',['What causes the contact?','How many times in the last five workdays?'],{unit:'operational contacts / week',healthy:'secondary evidence',severe:'review pattern',min:0,step:1}),
  q('Founder-Held Knowledge','Are there important processes that become difficult or impossible when the founder is unavailable?',['Which processes?','What knowledge is missing?','How many of five important processes depend mainly on the founder?'],{unit:'dependent processes out of 5',healthy:'≤ 1 of 5',severe:'≥ 3 of 5',min:0,max:5,step:1}),
  q('Finding Information','When you need a process, policy, template, decision, or other information to do your job, where do you look first?',['How do you identify the approved version?','Who do you ask when it cannot be found?']),
  q('Retrieval Time','Think about the last time you needed to find operational information. What were you looking for, and how long did it take?',['Was it current and usable immediately?','Did someone still need to clarify it?'],{unit:'minutes / retrieval attempt',healthy:'≤ 5',severe:'≥ 15',min:0,step:0.1}),
  q('Documentation Freshness','When you find documentation, how often is it accurate enough to use without correcting or interpreting it?',['Out of the last five uses, how many were materially outdated?','What consequence did the latest obsolete document create?'],{unit:'obsolete uses out of 5',healthy:'≤ 0.5 of 5',severe:'≥ 1.5 of 5',min:0,max:5,step:1}),
  q('Repeated Knowledge Requests','Is there someone on the team who gets asked the same questions repeatedly?',['Why do people use that person instead of a system?','What happens when they are unavailable?']),
  q('Process Ownership','For the processes you use most often, is it clear who owns them and who should update them when something changes?',['Who decides the correct process?','Where are there multiple or missing owners?']),
  q('Onboarding Experience','How long does it usually take a new person in this role to perform the core recurring work independently?',['What signaled autonomy?','What slowed the latest case?'],{unit:'calendar days to autonomy',healthy:'≤ 14',severe:'≥ 42',min:0,step:1}),
  q('Recent Project Walkthrough','Walk me through a recent project from the moment you received it until it was completed or reached its current state.',['What was missing initially?','Where did it pause, change, or require rework?']),
  q('Forced Stops','During that project, how many times were you forced to stop because a decision, dependency, permission, input, resource, or handoff was missing?',['Count only when meaningful work could not continue.','What caused each stop?'],{unit:'forced stops / project',healthy:'≤ 1',severe:'≥ 3',min:0,step:1}),
  q('Avoidable Rework','How much of the work on that project had to be redone because the original brief, handoff, decision, or information was insufficient?',['Exclude normal refinement and new external information.','How many rework hours versus total hours?'],{unit:'% of project effort',healthy:'≤ 10%',severe:'≥ 30%',min:0,max:100,step:1}),
  q('Alignment Drift','How often does work have to pause, reverse, or materially change because people discovered they were not aligned on purpose, priority, scope, or definition of success?',['How many times last month?','Across how many active projects?'],{unit:'events / project / month',healthy:'≤ 1',severe:'≥ 3',min:0,step:0.1}),
  q('Tool Context-Switching','Walk me through one recurring task that requires you to move between multiple software tools.',['Which transitions are avoidable?','How much time is spent relocating or reconstructing information?'],{unit:'avoidable minutes / workday',healthy:'≤ 15',severe:'≥ 45',min:0,max:1440,step:1}),
  q('Manual Work and Integration Integrity','What information do you regularly copy, re-enter, reformat, or manually move between tools?',['Which tools should exchange it automatically?','How are failures noticed and corrected?']),
  q('Tool Utility and Overlap','Are there tools that overlap, are rarely useful, or create more effort than the value they provide?',['What would break if each disappeared?','Is low use appropriate for a specialized function?']),
  q('Recent Handoff','Think about the most recent time you received work from someone else or handed work to another person. Walk me through what happened.',['What context came with it?','Were deadline and success criteria clear?']),
  q('Handoff Context Loss','On a scale from 1 to 5, how would you rate context loss in the handoffs you receive?',['What is most commonly missing?','What did you reconstruct in the specific handoff?'],{unit:'context-loss rating (1–5)',healthy:'≤ 2',severe:'5',min:1,max:5,step:1}),
  q('Clarification Time','In that handoff, how much active time did you and the other person spend clarifying what was needed before work could proceed confidently?',['Include cumulative active time for everyone involved.','How much elapsed delay occurred?'],{unit:'person-hours / handoff',healthy:'≤ 1',severe:'≥ 3',min:0,step:0.1}),
  q('Handoff Confidence','Before you inspect the details, how confident are you that a typical incoming handoff will contain enough accurate information and context to proceed without preventable clarification or rework?',['What drives that percentage?','How does it vary by team or workflow?'],{unit:'confidence %',healthy:'≥ 90%',severe:'0%',min:0,max:100,step:1}),
  q('How the System Is Kept Working','When the official process, documentation, tool, or handoff is not enough, what do you personally do to make sure the work still gets done?',['What private trackers, checks, meetings, or reconciliations do you maintain?','What happens if you stop?']),
  q('Highest-Leverage Change','If you could fix one thing about how this company operates, what would you fix?',['Why that one?','Who is most affected now?']),
  q('Missing Question','What should I understand about how work happens here that I haven’t asked about?'),
  q('Evidence Permission and Follow-Up','Which named artifacts may I review, and may I contact you for clarification?',['Does any statement require special confidentiality?','Which example is most representative?'])
];
export const STAFF_INTERVIEW_SECTIONS = [
  {id:'operating_rhythm',title:'Role and operating rhythm',question:'Walk me through your role and what a typical week and workday look like.',promptIndexes:[0,1]},
  {id:'decisions_founder',title:'Decisions and founder dependency',question:'When work needs a decision, clarification, or founder-held knowledge, what happens?',promptIndexes:[2,3,4,5]},
  {id:'knowledge_system',title:'Knowledge access, quality, and ownership',question:'How do you find reliable operational information, and who keeps it current?',promptIndexes:[6,7,8,9,10]},
  {id:'onboarding',title:'Onboarding',question:'How does someone in this role become independently effective?',promptIndexes:[11]},
  {id:'project_flow',title:'Recent project flow',question:'Walk me through a recent project, including where it stopped, changed direction, or required rework.',promptIndexes:[12,13,14,15]},
  {id:'tools_integrations',title:'Tools and integrations',question:'Walk me through how tools support—or complicate—one recurring workflow.',promptIndexes:[16,17,18]},
  {id:'handoffs',title:'Handoffs',question:'Walk me through a recent handoff and the context or clarification it required.',promptIndexes:[19,20,21,22]},
  {id:'workarounds',title:'Workarounds and compensating mechanisms',question:'What do you personally do when the official process, documentation, tool, or handoff is not enough?',promptIndexes:[23]},
  {id:'highest_leverage',title:'Highest-leverage change',question:'If you could fix one thing about how this company operates, what would you fix?',promptIndexes:[24]},
  {id:'closing',title:'Missing context, evidence, and follow-up',question:'What have I missed, what evidence may I review, and may I follow up with you?',promptIndexes:[25,26]}
];
export const SAMPLE_TYPES = {criticalOperations:'Critical operations',decisionEvents:'Decision events',documents:'Documents',retrievalTests:'Retrieval tests',projects:'Projects',toolWorkflows:'Tool workflows',tools:'Tools',integrations:'Integrations',handoffs:'Handoffs',onboardingCases:'Onboarding cases'};
const now = () => new Date().toISOString();
export const uid = (prefix='rec') => `${prefix}_${crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2)}`;

export function blankDiagnosis() {
  const createdAt=now();
  return {...VERSIONS,createdAt,updatedAt:createdAt,lastCompletedStep:'',engagement:{companyName:'',founderSponsor:'',primaryContact:'',startDate:'',deliveryDate:'',companySize:'',businessModel:'',communicationPlatform:'',documentationPlatform:'',taskPlatform:'',confidentialityRestrictions:'',practitionerNotes:'',practitioner:'',status:'not_started',nextAction:''},readiness:{requirements:Object.fromEntries(REQUIREMENTS.map(([id,label,category])=>[id,{id,label,category,status:'',notes:'',reasonUnavailable:'',alternativeSource:'',metricsAffected:'',confidenceImpact:''}]))},founderIntake:{sections:Object.fromEntries(FOUNDER_SECTIONS.map((prompt,i)=>[`f${i+1}`,{id:`f${i+1}`,title:prompt.title,question:prompt.question,response:'',quantitativeEstimate:'',unit:prompt.quantitative?.unit||'',timePeriod:'',confidence:'',recentExample:'',artifactCandidate:'',metricsInformed:'',followUp:false,practitionerNote:'',notApplicable:false,skipReason:'',validationLeadRequested:false}]))},validationLeads:[],staffInterviews:[],evidence:[],samples:Object.fromEntries(Object.keys(SAMPLE_TYPES).map(key=>[key,[]])),convergences:[],contradictions:[],limitations:[],metricRecords:Object.fromEntries(METRICS.map(metric=>[metric.id,{metricId:metric.id,state:'not_started',calculatedValue:'',estimatedValue:'',estimationMethod:'',confidence:'unavailable',evidenceBasis:'',sampleSize:'',samplePeriod:'',limitation:'',overrideValue:'',overrideReason:'',clientSafeReviewed:false}])),dimensionResults:{},selectedDrivers:[],findings:[],compensatingMechanisms:[],recommendations:[],reportDraft:{executiveObservation:'',operationalImpact:'',immediatePriority:'',scoreInterpretation:'',dimensionNarratives:{},engagementPathway:'',clientSafeReviewed:false},workflowState:{activeView:'overview',days:{day0:'not_started',day1:'not_started',day2:'not_started',day3:'not_started',day4:'not_started',report:'not_started'},lastCheckpointExportAt:null,dirty:false},migrationWarnings:[]};
}
export function baseRecord(sourceDay,extra={}){const t=now();return{id:uid('rec'),createdAt:t,updatedAt:t,sourceDay,status:'in_progress',practitionerNotes:'',...extra};}

export function interviewStatusAfterScheduling(currentStatus,scheduledTime){
  return scheduledTime&&(!currentStatus||currentStatus==='not_scheduled')?'scheduled':currentStatus;
}

export function projectMonthsFromWeeks(sampledWeeks){
  return sampledWeeks!==''&&sampledWeeks!=null&&Number.isFinite(Number(sampledWeeks))?Number((Number(sampledWeeks)/(365.2425/12/7)).toFixed(4)):'';
}

export function clearSkippedFounderSection(section){
  if(!section?.notApplicable)return section;
  Object.assign(section,{response:'',quantitativeEstimate:'',confidence:'',timePeriod:'',recentExample:'',artifactCandidate:'',metricsInformed:'',practitionerNote:''});
  return section;
}

const validationLeadWorked=lead=>lead.status!=='not_started'||Boolean(String(lead.validationNotes||'').trim())||Boolean(lead.evidenceId);
export function syncFounderValidationLead(state,sectionId,requested=true){
  state.validationLeads||=[];
  const section=state.founderIntake.sections[sectionId],index=state.validationLeads.findIndex(lead=>lead.sourceSectionId===sectionId),existing=state.validationLeads[index];
  section.validationLeadRequested=Boolean(requested)&&!section.notApplicable;
  if(!section.validationLeadRequested){
    if(existing){if(validationLeadWorked(existing)){Object.assign(existing,{inactive:true,inactiveReason:section.notApplicable?'Source question skipped':'Lead deselected'});const evidenceIndex=state.evidence?.findIndex(record=>record.id===existing.evidenceId)??-1;if(evidenceIndex>=0){existing.inactiveEvidence=state.evidence[evidenceIndex];state.evidence.splice(evidenceIndex,1)}}else state.validationLeads.splice(index,1)}
    return existing||null;
  }
  const source={sourceSectionId:sectionId,sourceQuestion:section.question,claim:section.response||'',quantitativeEstimate:section.quantitativeEstimate??'',unit:section.unit||'',confidence:section.confidence||'',artifactCandidate:section.artifactCandidate||''};
  if(existing){if(!validationLeadWorked(existing))Object.assign(existing,source);Object.assign(existing,{inactive:false,inactiveReason:''});if(existing.inactiveEvidence&&!state.evidence?.some(record=>record.id===existing.evidenceId)){state.evidence||=[];state.evidence.push(existing.inactiveEvidence);delete existing.inactiveEvidence}return existing}
  const lead=baseRecord('day1',{...source,status:'not_started',validationNotes:'',inactive:false,inactiveReason:'',evidenceId:''});state.validationLeads.push(lead);return lead;
}

export function skipFounderSection(state,sectionId){
  const section=state.founderIntake.sections[sectionId];section.notApplicable=true;syncFounderValidationLead(state,sectionId,false);clearSkippedFounderSection(section);return section;
}

const enumPaths=[['engagement.status','diagnosisStatus'],['readiness.requirements.*.status','requirementStatus'],['staffInterviews.*.status','interviewStatus'],['validationLeads.*.status','validationLeadStatus'],['evidence.*.evidenceType','evidenceType'],['evidence.*.confidence','confidence'],['metricRecords.*.state','metricState'],['metricRecords.*.confidence','confidence'],['samples.criticalOperations.*.founderMemoryDependent','founderMemory'],['samples.documents.*.obsolescenceStatus','documentStatus'],['samples.documents.*.obsolete','documentStatus'],['samples.tools.*.classification','toolClassification'],['samples.integrations.*.outcome','integrationOutcome'],['samples.integrations.*.success','integrationOutcome'],['recommendations.*.level','recommendationLevel'],['recommendations.*.priority','priority']];
function visit(root,parts,callback,path=[]){if(!parts.length)return callback(root,path);const[head,...tail]=parts;if(head==='*')Object.keys(root||{}).forEach(key=>visit(root[key],tail,callback,[...path,key]));else if(root&&Object.hasOwn(root,head))visit(root[head],tail,callback,[...path,head]);}
function setAt(root,path,value){let cursor=root;for(let i=0;i<path.length-1;i++)cursor=cursor[path[i]];cursor[path.at(-1)]=value;}
function migrateInterviewSections(interview){interview.responses||={};interview.responseQuantitative||={};interview.responseArtifacts||={};interview.responseEvidence||={};interview.sectionResponses||={};interview.sectionQuantitative||={};interview.sectionArtifacts||={};interview.sectionEvidence||={};STAFF_INTERVIEW_SECTIONS.forEach((section,sectionIndex)=>{if(!interview.sectionResponses[sectionIndex])interview.sectionResponses[sectionIndex]=section.promptIndexes.map(index=>interview.responses[index]?`${STAFF_PROMPTS[index].title}: ${interview.responses[index]}`:'').filter(Boolean).join('\n\n');interview.sectionQuantitative[sectionIndex]||={};for(const index of section.promptIndexes)if(interview.responseQuantitative[index]&&interview.sectionQuantitative[sectionIndex][index]==null)interview.sectionQuantitative[sectionIndex][index]=interview.responseQuantitative[index];if(!interview.sectionArtifacts[sectionIndex])interview.sectionArtifacts[sectionIndex]=section.promptIndexes.map(index=>interview.responseArtifacts[index]?`${STAFF_PROMPTS[index].title}: ${interview.responseArtifacts[index]}`:'').filter(Boolean).join('\n\n');if(interview.sectionEvidence[sectionIndex]==null)interview.sectionEvidence[sectionIndex]=section.promptIndexes.some(index=>Boolean(interview.responseEvidence[index]));});}
export function migrateCheckpoint(data){const migrated=structuredClone(data),warnings=[];migrated.validationLeads||=[];for(const[pattern,enumName]of enumPaths)visit(migrated,pattern.split('.'),(value,path)=>{const result=normalizeEnum(enumName,value);if(result.changed)setAt(migrated,path,result.value);else if(result.unknown)warnings.push({path:path.join('.'),enum:enumName,originalValue:value,message:`Unrecognized ${enumName} value preserved for repair.`});});for(const integration of migrated.samples?.integrations||[]){if(integration.success&&!integration.outcome)integration.outcome=normalizeEnum('integrationOutcome',integration.success).value;delete integration.success;}for(const document of migrated.samples?.documents||[]){if(document.obsolete&&!document.obsolescenceStatus)document.obsolescenceStatus=normalizeEnum('documentStatus',document.obsolete).value;delete document.obsolete;}migrated.founderIntake||={sections:{}};migrated.founderIntake.sections||={};FOUNDER_SECTIONS.forEach((prompt,index)=>{const id=`f${index+1}`;migrated.founderIntake.sections[id]||={id,response:'',quantitativeEstimate:'',confidence:'',artifactCandidate:'',practitionerNote:'',notApplicable:false,skipReason:'',validationLeadRequested:false};const section=migrated.founderIntake.sections[id];if(section.recentExample){const example=`Most recent example: ${section.recentExample}`;if(!String(section.response||'').includes(example))section.response=[section.response,example].filter(Boolean).join('\n\n');delete section.recentExample}section.notApplicable=Boolean(section.notApplicable);section.validationLeadRequested=Boolean(section.validationLeadRequested);Object.assign(section,{title:prompt.title,question:prompt.question,unit:prompt.quantitative?.unit||''});if(section.notApplicable)skipFounderSection(migrated,id);});for(const lead of migrated.validationLeads){lead.inactive=Boolean(lead.inactive);lead.inactiveReason||='';lead.validationNotes||='';lead.evidenceId||=''}for(const interview of migrated.staffInterviews||[])migrateInterviewSections(interview);for(const evidence of migrated.evidence||[]){evidence.confirmed=Boolean(evidence.confirmed);evidence.contradictionSelected=false;}migrated.schemaVersion='0.5';migrated.workspaceVersion='0.5';migrated.migrationWarnings=[...(migrated.migrationWarnings||[]),...warnings];return{data:migrated,warnings};}
export function validateRequirement(record){const errors=[];if(record.status&&!isEnumValue('requirementStatus',record.status))errors.push('Unrecognized requirement status.');if(REQUIREMENT_LIMITATION_STATUSES.has(record.status)&&!String(record.notes||record.reasonUnavailable||'').trim())errors.push('Impact, limitation, or reason is required for this status.');return errors;}
export function validateCheckpoint(data){const errors=[],warnings=[];if(!data||typeof data!=='object')errors.push('File must contain a JSON object.');for(const key of ['schemaVersion','workspaceVersion','metricDictionaryVersion','scoringSpecVersion','engagement','samples','metricRecords','workflowState'])if(data?.[key]==null)errors.push(`Missing required field: ${key}`);if(data?.schemaVersion&&!['0.1','0.2','0.3','0.4','0.5'].includes(data.schemaVersion))errors.push(`Unsupported schema version ${data.schemaVersion}; expected 0.1 through 0.5.`);for(const key of ['metricDictionaryVersion','scoringSpecVersion','reportTemplateVersion'])if(data?.[key]&&data[key]!==VERSIONS[key])warnings.push(`${key} is ${data[key]}; current is ${VERSIONS[key]}. Scores will not be recalculated automatically.`);if(['0.1','0.2','0.3','0.4'].includes(data?.schemaVersion))warnings.push(`Checkpoint schema ${data.schemaVersion} will be migrated to workspace schema 0.5; historical scores will not be recalculated.`);const checks=[['diagnosisStatus',data?.engagement?.status],...Object.values(data?.readiness?.requirements||{}).map(r=>['requirementStatus',r.status]),...Object.values(data?.validationLeads||{}).map(r=>['validationLeadStatus',r.status]),...Object.values(data?.metricRecords||{}).flatMap(r=>[['metricState',r.state],['confidence',r.confidence]])];for(const[name,value]of checks)if(value!==''&&value!=null&&!isEnumValue(name,value)&&normalizeEnum(name,value).unknown)warnings.push(`Unrecognized ${name} value: ${String(value)}.`);if(data&&typeof data==='object')for(const warning of migrateCheckpoint(data).warnings)warnings.push(`${warning.path}: ${warning.message}`);return{valid:errors.length===0,errors,warnings:[...new Set(warnings)]};}
