import {VERSIONS, METRICS} from './scoring.mjs';
import {isEnumValue, normalizeEnum, REQUIREMENT_LIMITATION_STATUSES} from './enums.mjs';

export const REQUIREMENTS = [
  ['communication_access','Primary communication-tool access','Required'], ['history_30_days','Minimum 30 days of operational history','Required'], ['founder_calendar','Founder calendar covering two representative weeks','Required'], ['task_access','Task-management access','Required'], ['operational_boards','Relevant operational boards','Required'], ['staff_interviews','3-5 staff interviews','Required'], ['founder_intake','60-90 minute founder intake','Required'], ['company_structure','Company hierarchy or staff structure','Required'], ['documentation_access','Internal documentation access','Strongly recommended'], ['tool_inventory','Active-tool inventory','Strongly recommended'], ['org_chart','Org chart or reporting description','Strongly recommended'], ['sprint_reports','Sprint reports or retrospectives','Useful'], ['process_docs','Process documentation','Useful'], ['onboarding_records','Onboarding records','Useful'], ['tool_usage','Tool-usage data','Useful'], ['prior_assessments','Prior operational assessments','Useful'], ['workflow_surveys','Existing workflow surveys','Useful']
];
export const FOUNDER_SECTIONS = ['Company and operating context','Engagement trigger','Intended versus actual operating model','Founder’s intended role','Founder’s actual week','Operational interruptions','Decision bottlenecks','Founder-unavailable test','Critical recurring processes','Knowledge and documentation','Company structure','Interview-participant selection','Onboarding cases','Representative projects','Workflow stops','Rework','Alignment drift','Tool inventory','Tool workflows','Integrations','Tool utility','Critical handoffs','Compensating mechanisms','Prior fixes','Scalability ceiling','Highest-leverage change','Successful diagnosis','Missing context'];
export const STAFF_PROMPTS = ['Typical work','Start and end of day','Decision routing','Blocked time waiting for decisions','Founder interruptions','Founder-held knowledge','Finding information','Retrieval time','Documentation freshness','Repeated knowledge requests','Process ownership','Onboarding experience','Recent project walkthrough','Forced stops','Avoidable rework','Alignment drift','Tool context-switching','Manual work and integration integrity','Tool utility and overlap','Recent handoff','Handoff context loss','Clarification time','Handoff confidence','How the system is kept working','Highest-leverage change','Missing question','Evidence permission and follow-up'];
export const SAMPLE_TYPES = {criticalOperations:'Critical operations',decisionEvents:'Decision events',documents:'Documents',retrievalTests:'Retrieval tests',projects:'Projects',toolWorkflows:'Tool workflows',tools:'Tools',integrations:'Integrations',handoffs:'Handoffs',onboardingCases:'Onboarding cases'};
const now = () => new Date().toISOString();
export const uid = (prefix='rec') => `${prefix}_${crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2)}`;

export function blankDiagnosis() {
  const createdAt=now();
  return {...VERSIONS,createdAt,updatedAt:createdAt,lastCompletedStep:'',engagement:{companyName:'',founderSponsor:'',primaryContact:'',startDate:'',deliveryDate:'',companySize:'',businessModel:'',communicationPlatform:'',documentationPlatform:'',taskPlatform:'',confidentialityRestrictions:'',practitionerNotes:'',practitioner:'',status:'not_started',nextAction:''},readiness:{requirements:Object.fromEntries(REQUIREMENTS.map(([id,label,category])=>[id,{id,label,category,status:'',notes:'',reasonUnavailable:'',alternativeSource:'',metricsAffected:'',confidenceImpact:''}]))},founderIntake:{sections:Object.fromEntries(FOUNDER_SECTIONS.map((label,i)=>[`f${i+1}`,{id:`f${i+1}`,label,response:'',quantitativeEstimate:'',unit:'',timePeriod:'',confidence:'',recentExample:'',artifactCandidate:'',metricsInformed:'',followUp:false,practitionerNote:'',notApplicable:false,skipReason:''}]))},staffInterviews:[],evidence:[],samples:Object.fromEntries(Object.keys(SAMPLE_TYPES).map(key=>[key,[]])),convergences:[],contradictions:[],limitations:[],metricRecords:Object.fromEntries(METRICS.map(metric=>[metric.id,{metricId:metric.id,state:'not_started',calculatedValue:'',estimatedValue:'',estimationMethod:'',confidence:'unavailable',evidenceBasis:'',sampleSize:'',samplePeriod:'',limitation:'',overrideValue:'',overrideReason:'',clientSafeReviewed:false}])),dimensionResults:{},selectedDrivers:[],findings:[],compensatingMechanisms:[],recommendations:[],reportDraft:{executiveObservation:'',operationalImpact:'',immediatePriority:'',scoreInterpretation:'',dimensionNarratives:{},engagementPathway:'',clientSafeReviewed:false},workflowState:{activeView:'overview',days:{day0:'not_started',day1:'not_started',day2:'not_started',day3:'not_started',day4:'not_started',report:'not_started'},lastCheckpointExportAt:null,dirty:false},migrationWarnings:[]};
}
export function baseRecord(sourceDay,extra={}){const t=now();return{id:uid('rec'),createdAt:t,updatedAt:t,sourceDay,status:'in_progress',practitionerNotes:'',...extra};}

const enumPaths=[['engagement.status','diagnosisStatus'],['readiness.requirements.*.status','requirementStatus'],['staffInterviews.*.status','interviewStatus'],['evidence.*.evidenceType','evidenceType'],['evidence.*.confidence','confidence'],['metricRecords.*.state','metricState'],['metricRecords.*.confidence','confidence'],['samples.criticalOperations.*.founderMemoryDependent','founderMemory'],['samples.documents.*.obsolescenceStatus','documentStatus'],['samples.documents.*.obsolete','documentStatus'],['samples.tools.*.classification','toolClassification'],['samples.integrations.*.outcome','integrationOutcome'],['samples.integrations.*.success','integrationOutcome'],['recommendations.*.level','recommendationLevel'],['recommendations.*.priority','priority']];
function visit(root,parts,callback,path=[]){if(!parts.length)return callback(root,path);const[head,...tail]=parts;if(head==='*')Object.keys(root||{}).forEach(key=>visit(root[key],tail,callback,[...path,key]));else if(root&&Object.hasOwn(root,head))visit(root[head],tail,callback,[...path,head]);}
function setAt(root,path,value){let cursor=root;for(let i=0;i<path.length-1;i++)cursor=cursor[path[i]];cursor[path.at(-1)]=value;}
export function migrateCheckpoint(data){const migrated=structuredClone(data),warnings=[];for(const[pattern,enumName]of enumPaths)visit(migrated,pattern.split('.'),(value,path)=>{const result=normalizeEnum(enumName,value);if(result.changed)setAt(migrated,path,result.value);else if(result.unknown)warnings.push({path:path.join('.'),enum:enumName,originalValue:value,message:`Unrecognized ${enumName} value preserved for repair.`});});for(const integration of migrated.samples?.integrations||[]){if(integration.success&&!integration.outcome)integration.outcome=normalizeEnum('integrationOutcome',integration.success).value;delete integration.success;}for(const document of migrated.samples?.documents||[]){if(document.obsolete&&!document.obsolescenceStatus)document.obsolescenceStatus=normalizeEnum('documentStatus',document.obsolete).value;delete document.obsolete;}migrated.schemaVersion='0.2';migrated.workspaceVersion='0.2';migrated.migrationWarnings=[...(migrated.migrationWarnings||[]),...warnings];return{data:migrated,warnings};}
export function validateRequirement(record){const errors=[];if(record.status&&!isEnumValue('requirementStatus',record.status))errors.push('Unrecognized requirement status.');if(REQUIREMENT_LIMITATION_STATUSES.has(record.status)&&!String(record.notes||record.reasonUnavailable||'').trim())errors.push('Impact, limitation, or reason is required for this status.');return errors;}
export function validateCheckpoint(data){const errors=[],warnings=[];if(!data||typeof data!=='object')errors.push('File must contain a JSON object.');for(const key of ['schemaVersion','workspaceVersion','metricDictionaryVersion','scoringSpecVersion','engagement','samples','metricRecords','workflowState'])if(data?.[key]==null)errors.push(`Missing required field: ${key}`);if(data?.schemaVersion&&!['0.1','0.2'].includes(data.schemaVersion))errors.push(`Unsupported schema version ${data.schemaVersion}; expected 0.1 or 0.2.`);for(const key of ['metricDictionaryVersion','scoringSpecVersion','reportTemplateVersion'])if(data?.[key]&&data[key]!==VERSIONS[key])warnings.push(`${key} is ${data[key]}; current is ${VERSIONS[key]}. Scores will not be recalculated automatically.`);if(data?.schemaVersion==='0.1')warnings.push('Checkpoint schema 0.1 will be migrated to controlled enum values; historical scores will not be recalculated.');const checks=[['diagnosisStatus',data?.engagement?.status],...Object.values(data?.readiness?.requirements||{}).map(r=>['requirementStatus',r.status]),...Object.values(data?.metricRecords||{}).flatMap(r=>[['metricState',r.state],['confidence',r.confidence]])];for(const[name,value]of checks)if(value!==''&&value!=null&&!isEnumValue(name,value)&&normalizeEnum(name,value).unknown)warnings.push(`Unrecognized ${name} value: ${String(value)}.`);if(data&&typeof data==='object')for(const warning of migrateCheckpoint(data).warnings)warnings.push(`${warning.path}: ${warning.message}`);return{valid:errors.length===0,errors,warnings:[...new Set(warnings)]};}
