export const VERSIONS={schemaVersion:'0.3',workspaceVersion:'0.3',metricDictionaryVersion:'0.1',scoringSpecVersion:'0.1',reportTemplateVersion:'0.1'};
export const DIMENSIONS=[
 {id:'founder',label:'Founder Dependency',weight:.30,metrics:[['decision_drag','Decision Blockage Time','blocked person-hours / contributor / week','higher_worse',2,6,0],['context_switching','Founder Context-Switching Frequency','interruptions / founder workday','higher_worse',3,9,0],['implicit_logic','Reliance on Institutional Memory','% of critical operations','higher_worse',20,60,0,100]]},
 {id:'knowledge',label:'Knowledge Logistics',weight:.20,metrics:[['discoverability_gap','Time to Find Source of Truth','minutes / retrieval attempt','higher_worse',5,15,0],['obsolescence_rate','Documentation Obsolescence','% materially obsolete','higher_worse',10,30,0,100],['onboarding_velocity','New-Hire Time to Impact','calendar days','higher_worse',14,42,0]]},
 {id:'velocity',label:'Workflow Velocity',weight:.20,metrics:[['interruption_count','Forced Stops per Project','forced stops / project','higher_worse',1,3,0],['rework_ratio','Rework Ratio','% of project effort','higher_worse',10,30,0,100],['alignment_drift','Alignment Drift Frequency','events / project / month','higher_worse',1,3,0]]},
 {id:'tools',label:'Tool Discipline',weight:.10,metrics:[['cognitive_load','Tool Context-Switching Tax','avoidable minutes / contributor / workday','higher_worse',15,45,0,1440],['integration_integrity','Data-Sync Integrity','% successful core data flows','lower_worse',95,0,0,100],['tool_utility','Tool Deadweight Factor','% active tools','higher_worse',20,60,0,100]]},
 {id:'handoff',label:'Handoff Integrity',weight:.20,metrics:[['context_loss','Handoff Context Loss','mean rating (1-5)','higher_worse',2,5,1,5],['clarification_cycle_time','Handoff Clarification Time','person-hours / handoff','higher_worse',1,3,0],['trust_in_handoff','Handoff Confidence Score','mean confidence %','lower_worse',90,0,0,100]]}
].map(d=>({...d,metrics:d.metrics.map(m=>({id:m[0],label:m[1],unit:m[2],direction:m[3],healthy:m[4],severe:m[5],min:m[6],max:m[7],dimensionId:d.id,dimensionLabel:d.label}))}));
export const METRICS=DIMENSIONS.flatMap(d=>d.metrics);
export const TIERS=[{max:2,label:'Structurally Sound'},{max:4,label:'Early Entropy'},{max:6,label:'Velocity Degradation'},{max:8,label:'Growth Ceiling Risk'},{max:10,label:'Structural Instability'}];
export const getTier=score=>score==null?null:(TIERS.find(t=>score<=t.max)||TIERS.at(-1));
export function normalizeScore(raw,healthy,severe,direction){if(raw===''||raw==null)return null;const value=Number(raw);if(!Number.isFinite(value))return null;const score=direction==='higher_worse'?2+((value-healthy)/(severe-healthy))*8:2+((healthy-value)/(healthy-severe))*8;return Math.max(2,Math.min(10,score));}
export function validateRaw(metric,raw){if(raw===''||raw==null)return'Missing value';const n=Number(raw);if(!Number.isFinite(n))return'Enter a numeric value';if(n<metric.min)return`Minimum permitted value is ${metric.min}`;if(metric.max!=null&&n>metric.max)return`Maximum permitted value is ${metric.max}`;return null;}
export function evaluateMetric(record,metric){const original=record?.calculatedValue;const chosen=record?.state==='overridden'?record.overrideValue:(record?.state==='estimated'?record.estimatedValue:original);const error=validateRaw(metric,chosen);const score=error?null:normalizeScore(chosen,metric.healthy,metric.severe,metric.direction);const final=['confirmed','overridden'].includes(record?.state)&&['high','medium','low'].includes(record?.confidence)&&score!=null&&String(record?.evidenceBasis||'').trim()&&String(record?.sampleSize||record?.estimationMethod||'').trim()&&(record?.state!=='overridden'||String(record?.overrideReason||'').trim());return{raw:chosen,original,score,error,final:Boolean(final),state:record?.state||'not_started'};}
export function calculateOEI(records={}){const metricResults=METRICS.map(metric=>({...metric,...evaluateMetric(records[metric.id],metric),record:records[metric.id]||{}}));const dimensions=Object.fromEntries(DIMENSIONS.map(d=>{const rows=metricResults.filter(r=>r.dimensionId===d.id);const available=rows.filter(r=>r.score!=null);const final=rows.every(r=>r.final);return[d.id,{...d,entered:available.length,score:available.length?available.reduce((s,r)=>s+r.score,0)/available.length:null,final,missing:rows.filter(r=>r.score==null).map(r=>r.label)}]}));const availableDimensions=DIMENSIONS.filter(d=>dimensions[d.id].score!=null);const provisionalScore=availableDimensions.length?availableDimensions.reduce((s,d)=>s+dimensions[d.id].score*d.weight,0)/availableDimensions.reduce((s,d)=>s+d.weight,0):null;const final=metricResults.every(r=>r.final);const finalScore=final?DIMENSIONS.reduce((s,d)=>s+dimensions[d.id].score*d.weight,0):null;return{metricResults,dimensions,confirmedCount:metricResults.filter(r=>r.final).length,final,provisionalScore,finalScore,displayScore:finalScore??provisionalScore,tier:getTier(finalScore??provisionalScore),driverCandidates:metricResults.filter(r=>r.final).sort((a,b)=>b.score-a.score)};}
export function applyOverride(record,value,reason,practitioner){if(!String(reason||'').trim())throw new Error('Override reason is required');return{...record,originalCalculatedValue:record.calculatedValue,originalScore:record.calculatedValue==null?null:normalizeScore(record.calculatedValue,record.metric.healthy,record.metric.severe,record.metric.direction),overrideValue:Number(value),overrideReason:reason,overridePractitioner:practitioner,overrideTimestamp:new Date().toISOString(),state:'overridden'};}
